import type { ZeoRole } from "../drizzle/schema";

// ─── Permission Definitions ─────────────────────────────────────────────────
export const PERMISSIONS = {
  // User Management
  USERS_VIEW: "users:view",
  USERS_MANAGE: "users:manage",
  USERS_ASSIGN_ROLES: "users:assign_roles",

  // Staff / HRM
  STAFF_VIEW_ALL: "staff:view_all",
  STAFF_VIEW_OWN: "staff:view_own",
  STAFF_CREATE: "staff:create",
  STAFF_EDIT: "staff:edit",
  STAFF_DELETE: "staff:delete",

  // Service History
  SERVICE_VIEW: "service:view",
  SERVICE_MANAGE: "service:manage",

  // Leave
  LEAVE_APPLY: "leave:apply",
  LEAVE_VIEW_OWN: "leave:view_own",
  LEAVE_VIEW_ALL: "leave:view_all",
  LEAVE_APPROVE_SCHOOL: "leave:approve_school",
  LEAVE_APPROVE_ZONE: "leave:approve_zone",

  // Transfers
  TRANSFER_APPLY: "transfer:apply",
  TRANSFER_RECOMMEND: "transfer:recommend",
  TRANSFER_REVIEW: "transfer:review",
  TRANSFER_APPROVE: "transfer:approve",
  TRANSFER_VIEW_ALL: "transfer:view_all",

  // Schools
  SCHOOLS_VIEW: "schools:view",
  SCHOOLS_MANAGE: "schools:manage",

  // Departments
  DEPARTMENTS_VIEW: "departments:view",
  DEPARTMENTS_MANAGE: "departments:manage",

  // Announcements
  ANNOUNCEMENTS_VIEW: "announcements:view",
  ANNOUNCEMENTS_CREATE: "announcements:create",
  ANNOUNCEMENTS_MANAGE: "announcements:manage",

  // Notifications
  NOTIFICATIONS_VIEW: "notifications:view",
  NOTIFICATIONS_SEND: "notifications:send",

  // Messages
  MESSAGES_SEND: "messages:send",
  MESSAGES_VIEW_OWN: "messages:view_own",

  // Students / SIS
  STUDENT_VIEW: "student:view",
  STUDENT_MANAGE: "student:manage",

  // Attendance
  ATTENDANCE_VIEW: "attendance:view",
  ATTENDANCE_MARK: "attendance:mark",

  // Grades
  GRADE_VIEW: "grade:view",
  GRADE_MANAGE: "grade:manage",

  // Scholarships
  SCHOLARSHIP_VIEW: "scholarship:view",
  SCHOLARSHIP_MANAGE: "scholarship:manage",
  SCHOLARSHIP_APPLY: "scholarship:apply",

  // Finance & Procurement
  BUDGET_VIEW: "budget:view",
  BUDGET_MANAGE: "budget:manage",
  TRANSACTION_VIEW: "transaction:view",
  TRANSACTION_CREATE: "transaction:create",
  SALARY_VIEW: "salary:view",
  SALARY_MANAGE: "salary:manage",
  VENDOR_VIEW: "vendor:view",
  VENDOR_MANAGE: "vendor:manage",
  PROCUREMENT_VIEW: "procurement:view",
  PROCUREMENT_CREATE: "procurement:create",
  PROCUREMENT_APPROVE: "procurement:approve",

  // School Supervision & QA
  INSPECTION_VIEW: "inspection:view",
  INSPECTION_CONDUCT: "inspection:conduct",
  INSPECTION_MANAGE: "inspection:manage",
  IMPROVEMENT_VIEW: "improvement:view",
  IMPROVEMENT_MANAGE: "improvement:manage",
  SCORECARD_VIEW: "scorecard:view",
  SCORECARD_MANAGE: "scorecard:manage",

  // Analytics
  ANALYTICS_VIEW: "analytics:view",
  ANALYTICS_VIEW_ZONE: "analytics:view_zone",
  ANALYTICS_VIEW_SCHOOL: "analytics:view_school",

  // Audit
  AUDIT_VIEW: "audit:view",

  // System
  SYSTEM_ADMIN: "system:admin",
} as const;

export type Permission = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

// ─── Role-Permission Matrix ─────────────────────────────────────────────────
export const ROLE_PERMISSIONS: Record<ZeoRole, Permission[]> = {
  admin: Object.values(PERMISSIONS),

  zonal_director: [
    PERMISSIONS.USERS_VIEW,
    PERMISSIONS.USERS_MANAGE,
    PERMISSIONS.USERS_ASSIGN_ROLES,
    PERMISSIONS.STAFF_VIEW_ALL,
    PERMISSIONS.STAFF_CREATE,
    PERMISSIONS.STAFF_EDIT,
    PERMISSIONS.SERVICE_VIEW,
    PERMISSIONS.SERVICE_MANAGE,
    PERMISSIONS.LEAVE_VIEW_ALL,
    PERMISSIONS.LEAVE_APPROVE_ZONE,
    PERMISSIONS.TRANSFER_VIEW_ALL,
    PERMISSIONS.TRANSFER_APPROVE,
    PERMISSIONS.SCHOOLS_VIEW,
    PERMISSIONS.SCHOOLS_MANAGE,
    PERMISSIONS.DEPARTMENTS_VIEW,
    PERMISSIONS.DEPARTMENTS_MANAGE,
    PERMISSIONS.ANNOUNCEMENTS_VIEW,
    PERMISSIONS.ANNOUNCEMENTS_CREATE,
    PERMISSIONS.ANNOUNCEMENTS_MANAGE,
    PERMISSIONS.NOTIFICATIONS_VIEW,
    PERMISSIONS.NOTIFICATIONS_SEND,
    PERMISSIONS.MESSAGES_SEND,
    PERMISSIONS.MESSAGES_VIEW_OWN,
    PERMISSIONS.ANALYTICS_VIEW,
    PERMISSIONS.ANALYTICS_VIEW_ZONE,
    PERMISSIONS.ANALYTICS_VIEW_SCHOOL,
    PERMISSIONS.AUDIT_VIEW,
    PERMISSIONS.STUDENT_VIEW,
    PERMISSIONS.STUDENT_MANAGE,
    PERMISSIONS.ATTENDANCE_VIEW,
    PERMISSIONS.ATTENDANCE_MARK,
    PERMISSIONS.GRADE_VIEW,
    PERMISSIONS.GRADE_MANAGE,
    PERMISSIONS.SCHOLARSHIP_VIEW,
    PERMISSIONS.SCHOLARSHIP_MANAGE,
    PERMISSIONS.BUDGET_VIEW,
    PERMISSIONS.BUDGET_MANAGE,
    PERMISSIONS.TRANSACTION_VIEW,
    PERMISSIONS.TRANSACTION_CREATE,
    PERMISSIONS.SALARY_VIEW,
    PERMISSIONS.SALARY_MANAGE,
    PERMISSIONS.VENDOR_VIEW,
    PERMISSIONS.VENDOR_MANAGE,
    PERMISSIONS.PROCUREMENT_VIEW,
    PERMISSIONS.PROCUREMENT_CREATE,
    PERMISSIONS.PROCUREMENT_APPROVE,
    PERMISSIONS.INSPECTION_VIEW,
    PERMISSIONS.INSPECTION_CONDUCT,
    PERMISSIONS.INSPECTION_MANAGE,
    PERMISSIONS.IMPROVEMENT_VIEW,
    PERMISSIONS.IMPROVEMENT_MANAGE,
    PERMISSIONS.SCORECARD_VIEW,
    PERMISSIONS.SCORECARD_MANAGE,
  ],

  deputy_director: [
    PERMISSIONS.USERS_VIEW,
    PERMISSIONS.STAFF_VIEW_ALL,
    PERMISSIONS.STAFF_CREATE,
    PERMISSIONS.STAFF_EDIT,
    PERMISSIONS.SERVICE_VIEW,
    PERMISSIONS.SERVICE_MANAGE,
    PERMISSIONS.LEAVE_VIEW_ALL,
    PERMISSIONS.LEAVE_APPROVE_ZONE,
    PERMISSIONS.TRANSFER_VIEW_ALL,
    PERMISSIONS.TRANSFER_REVIEW,
    PERMISSIONS.SCHOOLS_VIEW,
    PERMISSIONS.DEPARTMENTS_VIEW,
    PERMISSIONS.ANNOUNCEMENTS_VIEW,
    PERMISSIONS.ANNOUNCEMENTS_CREATE,
    PERMISSIONS.NOTIFICATIONS_VIEW,
    PERMISSIONS.NOTIFICATIONS_SEND,
    PERMISSIONS.MESSAGES_SEND,
    PERMISSIONS.MESSAGES_VIEW_OWN,
    PERMISSIONS.ANALYTICS_VIEW,
    PERMISSIONS.ANALYTICS_VIEW_ZONE,
    PERMISSIONS.ANALYTICS_VIEW_SCHOOL,
    PERMISSIONS.STUDENT_VIEW,
    PERMISSIONS.STUDENT_MANAGE,
    PERMISSIONS.ATTENDANCE_VIEW,
    PERMISSIONS.GRADE_VIEW,
    PERMISSIONS.GRADE_MANAGE,
    PERMISSIONS.SCHOLARSHIP_VIEW,
    PERMISSIONS.SCHOLARSHIP_MANAGE,
    PERMISSIONS.BUDGET_VIEW,
    PERMISSIONS.BUDGET_MANAGE,
    PERMISSIONS.TRANSACTION_VIEW,
    PERMISSIONS.TRANSACTION_CREATE,
    PERMISSIONS.SALARY_VIEW,
    PERMISSIONS.SALARY_MANAGE,
    PERMISSIONS.VENDOR_VIEW,
    PERMISSIONS.VENDOR_MANAGE,
    PERMISSIONS.PROCUREMENT_VIEW,
    PERMISSIONS.PROCUREMENT_CREATE,
    PERMISSIONS.PROCUREMENT_APPROVE,
    PERMISSIONS.INSPECTION_VIEW,
    PERMISSIONS.INSPECTION_CONDUCT,
    PERMISSIONS.INSPECTION_MANAGE,
    PERMISSIONS.IMPROVEMENT_VIEW,
    PERMISSIONS.IMPROVEMENT_MANAGE,
    PERMISSIONS.SCORECARD_VIEW,
    PERMISSIONS.SCORECARD_MANAGE,
  ],

  branch_head: [
    PERMISSIONS.STAFF_VIEW_ALL,
    PERMISSIONS.STAFF_EDIT,
    PERMISSIONS.SERVICE_VIEW,
    PERMISSIONS.LEAVE_VIEW_ALL,
    PERMISSIONS.TRANSFER_VIEW_ALL,
    PERMISSIONS.TRANSFER_REVIEW,
    PERMISSIONS.SCHOOLS_VIEW,
    PERMISSIONS.DEPARTMENTS_VIEW,
    PERMISSIONS.ANNOUNCEMENTS_VIEW,
    PERMISSIONS.ANNOUNCEMENTS_CREATE,
    PERMISSIONS.NOTIFICATIONS_VIEW,
    PERMISSIONS.MESSAGES_SEND,
    PERMISSIONS.MESSAGES_VIEW_OWN,
    PERMISSIONS.ANALYTICS_VIEW_ZONE,
    PERMISSIONS.STUDENT_VIEW,
    PERMISSIONS.ATTENDANCE_VIEW,
    PERMISSIONS.GRADE_VIEW,
    PERMISSIONS.SCHOLARSHIP_VIEW,
    PERMISSIONS.BUDGET_VIEW,
    PERMISSIONS.TRANSACTION_VIEW,
    PERMISSIONS.PROCUREMENT_VIEW,
    PERMISSIONS.PROCUREMENT_CREATE,
    PERMISSIONS.INSPECTION_VIEW,
    PERMISSIONS.IMPROVEMENT_VIEW,
    PERMISSIONS.SCORECARD_VIEW,
  ],

  isa: [
    PERMISSIONS.STAFF_VIEW_ALL,
    PERMISSIONS.SERVICE_VIEW,
    PERMISSIONS.LEAVE_VIEW_ALL,
    PERMISSIONS.SCHOOLS_VIEW,
    PERMISSIONS.ANNOUNCEMENTS_VIEW,
    PERMISSIONS.ANNOUNCEMENTS_CREATE,
    PERMISSIONS.NOTIFICATIONS_VIEW,
    PERMISSIONS.MESSAGES_SEND,
    PERMISSIONS.MESSAGES_VIEW_OWN,
    PERMISSIONS.ANALYTICS_VIEW_SCHOOL,
    PERMISSIONS.STUDENT_VIEW,
    PERMISSIONS.ATTENDANCE_VIEW,
    PERMISSIONS.GRADE_VIEW,
    PERMISSIONS.SCHOLARSHIP_VIEW,
    PERMISSIONS.INSPECTION_VIEW,
    PERMISSIONS.INSPECTION_CONDUCT,
    PERMISSIONS.IMPROVEMENT_VIEW,
    PERMISSIONS.IMPROVEMENT_MANAGE,
    PERMISSIONS.SCORECARD_VIEW,
  ],

  principal: [
    PERMISSIONS.STAFF_VIEW_ALL,
    PERMISSIONS.STAFF_VIEW_OWN,
    PERMISSIONS.SERVICE_VIEW,
    PERMISSIONS.LEAVE_VIEW_OWN,
    PERMISSIONS.LEAVE_APPLY,
    PERMISSIONS.LEAVE_APPROVE_SCHOOL,
    PERMISSIONS.TRANSFER_RECOMMEND,
    PERMISSIONS.SCHOOLS_VIEW,
    PERMISSIONS.ANNOUNCEMENTS_VIEW,
    PERMISSIONS.ANNOUNCEMENTS_CREATE,
    PERMISSIONS.NOTIFICATIONS_VIEW,
    PERMISSIONS.MESSAGES_SEND,
    PERMISSIONS.MESSAGES_VIEW_OWN,
    PERMISSIONS.ANALYTICS_VIEW_SCHOOL,
    PERMISSIONS.STUDENT_VIEW,
    PERMISSIONS.STUDENT_MANAGE,
    PERMISSIONS.ATTENDANCE_VIEW,
    PERMISSIONS.ATTENDANCE_MARK,
    PERMISSIONS.GRADE_VIEW,
    PERMISSIONS.GRADE_MANAGE,
    PERMISSIONS.SCHOLARSHIP_VIEW,
    PERMISSIONS.SCHOLARSHIP_APPLY,
    PERMISSIONS.BUDGET_VIEW,
    PERMISSIONS.TRANSACTION_VIEW,
    PERMISSIONS.TRANSACTION_CREATE,
    PERMISSIONS.PROCUREMENT_VIEW,
    PERMISSIONS.PROCUREMENT_CREATE,
    PERMISSIONS.INSPECTION_VIEW,
    PERMISSIONS.IMPROVEMENT_VIEW,
    PERMISSIONS.SCORECARD_VIEW,
  ],

  teacher: [
    PERMISSIONS.STAFF_VIEW_OWN,
    PERMISSIONS.LEAVE_APPLY,
    PERMISSIONS.LEAVE_VIEW_OWN,
    PERMISSIONS.TRANSFER_APPLY,
    PERMISSIONS.SCHOOLS_VIEW,
    PERMISSIONS.ANNOUNCEMENTS_VIEW,
    PERMISSIONS.NOTIFICATIONS_VIEW,
    PERMISSIONS.MESSAGES_SEND,
    PERMISSIONS.MESSAGES_VIEW_OWN,
    PERMISSIONS.STUDENT_VIEW,
    PERMISSIONS.ATTENDANCE_VIEW,
    PERMISSIONS.ATTENDANCE_MARK,
    PERMISSIONS.GRADE_VIEW,
    PERMISSIONS.GRADE_MANAGE,
  ],

  parent: [
    PERMISSIONS.ANNOUNCEMENTS_VIEW,
    PERMISSIONS.NOTIFICATIONS_VIEW,
    PERMISSIONS.MESSAGES_SEND,
    PERMISSIONS.MESSAGES_VIEW_OWN,
    PERMISSIONS.STUDENT_VIEW,
    PERMISSIONS.ATTENDANCE_VIEW,
    PERMISSIONS.GRADE_VIEW,
    PERMISSIONS.SCHOLARSHIP_VIEW,
  ],

  student: [
    PERMISSIONS.ANNOUNCEMENTS_VIEW,
    PERMISSIONS.NOTIFICATIONS_VIEW,
    PERMISSIONS.MESSAGES_VIEW_OWN,
    PERMISSIONS.STUDENT_VIEW,
    PERMISSIONS.ATTENDANCE_VIEW,
    PERMISSIONS.GRADE_VIEW,
    PERMISSIONS.SCHOLARSHIP_VIEW,
    PERMISSIONS.SCHOLARSHIP_APPLY,
  ],

  user: [
    PERMISSIONS.ANNOUNCEMENTS_VIEW,
    PERMISSIONS.NOTIFICATIONS_VIEW,
  ],
};

// ─── Helper Functions ────────────────────────────────────────────────────────
export function hasPermission(role: ZeoRole, permission: Permission): boolean {
  return ROLE_PERMISSIONS[role]?.includes(permission) ?? false;
}

export function hasAnyPermission(role: ZeoRole, permissions: Permission[]): boolean {
  return permissions.some((p) => hasPermission(role, p));
}

export function hasAllPermissions(role: ZeoRole, permissions: Permission[]): boolean {
  return permissions.every((p) => hasPermission(role, p));
}

// ─── Role Hierarchy (higher number = higher authority) ───────────────────────
export const ROLE_HIERARCHY: Record<ZeoRole, number> = {
  admin: 100,
  zonal_director: 90,
  deputy_director: 80,
  branch_head: 70,
  isa: 60,
  principal: 50,
  teacher: 40,
  parent: 20,
  student: 10,
  user: 0,
};

export function isRoleHigherOrEqual(role: ZeoRole, targetRole: ZeoRole): boolean {
  return ROLE_HIERARCHY[role] >= ROLE_HIERARCHY[targetRole];
}

// ─── Role Display Names ─────────────────────────────────────────────────────
export const ROLE_DISPLAY_NAMES: Record<ZeoRole, string> = {
  admin: "System Administrator",
  zonal_director: "Zonal Director",
  deputy_director: "Deputy Director (Development)",
  branch_head: "Branch Head",
  isa: "In-Service Advisor (ISA)",
  principal: "Principal",
  teacher: "Teacher",
  parent: "Parent",
  student: "Student",
  user: "User",
};

// ─── Ordered list of all ZEO roles ──────────────────────────────────────────
export const ZEO_ROLES: ZeoRole[] = [
  "admin",
  "zonal_director",
  "deputy_director",
  "branch_head",
  "isa",
  "principal",
  "teacher",
  "parent",
  "student",
  "user",
];
